-- liquibase formatted sql

-- changeSet Vladislav:1
create table product(
    id int generated by default as identity PRIMARY KEY,
    name varchar not null,
    calories int not null,
    proteins float4 not null,
    fats float4 not null,
    carbohydrates float4 not null
);

-- rollback drop table product;