-- liquibase formatted sql

-- changeSet Vladislav:2

create table ration(
    ration_id int generated by default as identity primary key,
    person_id int references person(id) on delete cascade not null,
    product_id int references product(id) on delete cascade not null,
    weight int not null,
    datetime varchar,
    created timestamp without time zone
);

create index ration_person_id_date_idx on ration(person_id, created);

-- rollback drop table ration;