-- liquibase formatted sql

-- changeSet Vladislav:1

create type personRoles as ENUM('ADMIN', 'USER', 'COACH');

create table if not exists person(
    id int generated by default as identity primary key,
    coach_id int references person(id) on delete set null,
    email varchar not null unique,
    password varchar not null,
    phone int unique,
    name varchar not null,
    surname varchar not null,
    lastname varchar,
    birthdate date,
    address varchar,
    gender varchar,
    image varchar,
    description text,
    role personRoles not null
);

create index if not exists person_coach_id_index on person(coach_id);
create index if not exists person_email_index on person(email);

-- rollback drop table person;