-- liquibase formatted sql

-- changeSet Vladislav:2

create table if not exists parameter(
    id int generated by default as identity primary key,
    person_id int references person(id) on delete cascade not null,
    height float4,
    weight float4,
    calories int,
    measurement_date timestamp without time zone
);

create index if not exists parameter_person_id_index on parameter(person_id);

-- rollback drop index parameter_person_id_index;
-- rollback drop table parameter;