-- liquibase formatted sql

-- changeSet Vladislav:1

create table exercise(
    id bigint generated by default as identity primary key,
    name varchar not null,
    muscle_group varchar not null,
    description varchar not null,
    image varchar,
    example varchar,
    modified_date timestamp without time zone not null
);

-- rollback drop table exercise;