-- liquibase formatted sql

-- changeSet Vladislav:1

create table execution(
    execution_id bigint generated by default as identity PRIMARY KEY,
    person_id bigint references person(id) on delete cascade not null,
    exercise_id bigint references exercise(id) on delete cascade not null,
    repeats jsonb,
    creation_date timestamp without time zone not null
);

create index person_id_date_idx on execution(person_id, creation_date);

-- rollback drop index person_id_date_idx;
-- rollback drop table execution;